version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: MeetingAppDB
      MYSQL_USER: meetinguser
      MYSQL_PASSWORD: meetingpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init-mysql.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  api:
    build:
      context: .
      dockerfile: Meeting.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Container
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=MeetingAppDB;Uid=meetinguser;Pwd=meetingpass;AllowPublicKeyRetrieval=true;SslMode=none;
    depends_on:
      - mysql
    volumes:
      - api_uploads:/app/secure-uploads
    restart: on-failure

  web:
    build:
      context: .
      dockerfile: Meeting.Web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    restart: on-failure

volumes:
  mysql_data:
  api_uploads: